### PR TITLE
Discarded options from mcdo.sh in multiple operators (ccdo, space_ave…

### PR DESCRIPTION
**Pull request by jservonnat**
…rage, time_average...) to allow a more focused execution and avoid re-selecting the period (can cause issues when concatenating two periods)

### CODE REVIEW

**Comment by senesis** [comment]
Hi Jérôme
Are you sure that period concatenation is the only case with issues ?
How could we deal with that, especially when period concatenation is automatic (which is the case when asking twice for the same operations, first with one period, next with an extended period)

**Comment by jservonnat** [comment]
Hi Stephane,
the actual goals of this (at least, waiting for a better solution...) are:
- when concatenating manually (with a ncrcat operator declared with cscript), for instance an historical run and a scenario, the period of the object is the period of the historical run; if we apply one of the operators listed above, they will automatically re-extract the period of only the historical run; and we don't want that
- when we already have the dataset selected (period, variable and domain extracted), we don't need to redo it, especially when it is a big dataset

But there might be a better way to do it... I'm open to discussion, we just needed to propose a fix for some issues.

**Comment by senesis** [comment]
OK, I misunderstood your sentence `can cause issues when concatenating two periods` and thought that you had dully tested the side effects of your change

At first glance, I am very reluctant to the change, because this will neutralize a smart CliMAF feature, namely that applying e.g. ccdo to a dataset will be done using a cdo pipe operation at data selection stage (by mcdo.sh), and thus will avoid creating an intermediate file corresponding to the data selection (for variable period, ...) corresponding to dataset definition

I agree that this feature may be undesirable if data selection is the most time-consuming part and is reiterated.  But in that case, invoking `cfile` on the dataset maybe should solve the issue, by creating the intermediate file in the cache. Could you give a try ?

**Comment by senesis** [comment]
@jservonnat , @rigoudyg 
OK, CliMAF was faulty (from its early stage....) on re-using a dataset selection. A [dedicated commit](https://github.com/rigoudyg/climaf/pull/159/commits/5900b878000c09f54497e13f163176d5ae4f0a76) in #159  proposes a fix for that

**Comment by senesis** [comment]
The first issue (operators which concatenate) is fixed by #161 
 @jservonnat , I propose to close this PR.

**Pull request closed without merging**
